map = undefined
#创建和初始化地图函数：

initMap = ->
  createMap()
  #创建地图
  setMapEvent()
  #设置地图事件
  addMapControl()
  #向地图添加控件
  addMapOverlay()
  #向地图添加覆盖物
  return

createMap = ->
  map = new (BMap.Map)('baidu-map')
  map.centerAndZoom new (BMap.Point)(104.075249, 30.543281), 15
  return

setMapEvent = ->
  map.enableScrollWheelZoom()
  map.enableKeyboard()
  map.enableDragging()
  map.enableDoubleClickZoom()
  return

addClickHandler = (target, window) ->
  target.addEventListener 'click', ->
    target.openInfoWindow window
    return
  return

addMapOverlay = ->
  markers = [ {
    content: '400-008-0300'
    title: '成都库贝信息技术有限公司'
    imageOffset:
      width: 0
      height: 3
    position:
      lat: 30.541228
      lng: 104.075033
  } ]
  index = 0
  while index < markers.length
    point = new (BMap.Point)(markers[index].position.lng, markers[index].position.lat)
    marker = new (BMap.Marker)(point, icon: new (BMap.Icon)('http://api.map.baidu.com/lbsapi/createmap/images/icon.png', new (BMap.Size)(20, 25), imageOffset: new (BMap.Size)(markers[index].imageOffset.width, markers[index].imageOffset.height)))
    label = new (BMap.Label)(markers[index].title, offset: new (BMap.Size)(25, 5))
    opts =
      width: 200
      title: markers[index].title
      enableMessage: false
    infoWindow = new (BMap.InfoWindow)(markers[index].content, opts)
    marker.setLabel label
    addClickHandler marker, infoWindow
    map.addOverlay marker
    index++
  return

#向地图添加控件

addMapControl = ->
  scaleControl = new (BMap.ScaleControl)(anchor: BMAP_ANCHOR_BOTTOM_LEFT)
  scaleControl.setUnit BMAP_UNIT_IMPERIAL
  map.addControl scaleControl
  navControl = new (BMap.NavigationControl)(
    anchor: BMAP_ANCHOR_TOP_LEFT
    type: BMAP_NAVIGATION_CONTROL_LARGE)
  map.addControl navControl
  overviewControl = new (BMap.OverviewMapControl)(
    anchor: BMAP_ANCHOR_BOTTOM_RIGHT
    isOpen: true)
  map.addControl overviewControl
  return

initMap()

# ---
# generated by js2coffee 2.2.0